### PR TITLE
Translation of RVC into Portuguese in i18n

### PR DESCRIPTION
**Pull request by RafaelGodoyEbert**
# Pull request checklist

- [ ] The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- [ ] Make sure you are requesting the right branch: `dev`.
- [ ] Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- [ ] Ensure all tests are passing.
- [ ] Ensure linting is passing.

# PR type

Brazilian Portuguese language

# Description

Added the Brazilian Portuguese language to the project.

# Screenshot
image

### CODE REVIEW

**Review by Tps-F — APPROVED** [review]
Thank you!

**Comment by blaise-tk** [comment]
image
The translation has unnecessary things in addition to spam.

image

**Review by Tps-F — CHANGES_REQUESTED** [review]
Please remove unnecessary lines

**Comment by Tps-F** [comment]
@blaise-tk thank you for your review
I lose that

**Comment by RafaelGodoyEbert** [comment]
@fumiama I already added it, should I make a new PR? 
https://github.com/RafaelGodoyEbert/Retrieval-based-Voice-Conversion-WebUI/tree/main/docs/pt-BR

**Comment by fumiama** [comment]
> @fumiama I already added it, should I make a new PR? https://github.com/RafaelGodoyEbert/Retrieval-based-Voice-Conversion-WebUI/tree/main/docs/pt-BR

There're several README links at the beginning of README.md like this. See the last line. You can add Portuguese there.

<div align="center">

<h1>Retrieval-based-Voice-Conversion-WebUI</h1>
一个基于VITS的简单易用的变声框架<br><br>

[madewithlove](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI)

<br>

[Open In Colab](https://colab.research.google.com/github/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/Retrieval_based_Voice_Conversion_WebUI.ipynb)
[Licence](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/LICENSE)
[Huggingface](https://huggingface.co/lj1995/VoiceConversionWebUI/tree/main/)

[Discord](https://discord.gg/HcsmBBGyVk)

[**更新日志**](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/Changelog_CN.md) | [**常见问题解答**](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94) | [**AutoDL·5毛钱训练AI歌手**](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/Autodl%E8%AE%AD%E7%BB%83RVC%C2%B7AI%E6%AD%8C%E6%89%8B%E6%95%99%E7%A8%8B) | [**对照实验记录**](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/Autodl%E8%AE%AD%E7%BB%83RVC%C2%B7AI%E6%AD%8C%E6%89%8B%E6%95%99%E7%A8%8B](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/wiki/%E5%AF%B9%E7%85%A7%E5%AE%9E%E9%AA%8C%C2%B7%E5%AE%9E%E9%AA%8C%E8%AE%B0%E5%BD%95)) | [**在线演示**](https://modelscope.cn/studios/FlowerCry/RVCv2demo)

[**English**](./docs/en/README.en.md) | [**中文简体**](./README.md) | [**日本語**](./docs/jp/README.ja.md) | [**한국어**](./docs/kr/README.ko.md) ([**韓國語**](./docs/kr/README.ko.han.md)) | [**Français**](./docs/fr/README.fr.md) | [**Türkçe**](./docs/tr/README.tr.md)

</div>

**Comment by fumiama** [comment]
But don't worry. I will add that at my convinence.

**Pull request merged**
