### PR TITLE
replace PySimpleGUI with FreeSimpleGUI

### PR DESCRIPTION
**Pull request by deffcolony**
# Pull request checklist

- ✅ The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- ✅ Make sure you are requesting the right branch: `dev`.
- ✅ Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- ✅ Ensure all tests are passing.
- ✅ Ensure linting is passing.

# PR type

- new feature

# Description

This pull request will replace PySimpleGUI library into FreeSimpleGUI since PySimpleGUI became closed source and is not being updated anymore
https://www.reddit.com/r/Python/comments/1apng8d/pysimplegui_now_closedsource/

- What will it affect.
Replaces [PySimpleGUI](https://github.com/PySimpleGUI/PySimpleGUI) with [FreeSimpleGUI](https://github.com/spyoungtech/FreeSimpleGUI)

# Progress video

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/assets/61471128/457f75aa-2a3e-44dd-9d9a-1d2fc85e625d

### CODE REVIEW

**Comment by Tps-F** [comment]
Why are you want to replace it?

**Comment by LitCcc** [comment]
[https://docs.pysimplegui.com/en/latest/FAQ/](url)
PySimpleGUI now requires a (paid) license. If you do not register for a license, there will only be a 30-day trial period; I'm glad someone noticed this in the issues: #1931 #1909

**Comment by deffcolony** [comment]
@Tps-F As @LitCcc mentioned, you will currently get a window (paywall basically) stating that you need to register (establish an account) and that there will be a 30-day trial if you open any Python code containing a GUI created with PySimpleGUI. [PySimpleGUI became closed source](https://www.reddit.com/r/Python/comments/1apng8d/pysimplegui_now_closedsource/) and [FreeSimpleGUI](https://github.com/spyoungtech/FreeSimpleGUI) is a fork of PySimpleGUI with updates. Moreover, kindly view the video that my pull request links to. There is a noticeable difference between the import switch library that I changed.

**Comment by fumiama** [comment]
> PySimpleGUI now requires a (paid) license.

That's bad. Agree with you.

**Review by fumiama — APPROVED** [review]

**Comment by wastu01** [comment]
requirements.txt do not have any GUI is that right ?

**Comment by Tps-F** [comment]
@wastu01 
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/requirements-win-for-realtime_vc_gui.txt
Here

**Comment by wastu01** [comment]
because i am using M1 Mac and do not work.

**Comment by Tps-F** [comment]
Can you send me details of the error?
Or set up an issue and mentions me!

**Comment by FlynnHHH** [comment]
The https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/requirements-win-for-realtime_vc_gui.txt does not have FreeSimpleGPU now, I had to manually install it to use the real-time-gui.

(rvc-env) D:\RVC>pip install -r requirements-win-for-realtime_vc_gui.txt

(rvc-env) D:\RVC>python gui_v1.py
Traceback (most recent call last):
  File "D:\RVC\gui_v1.py", line 87, in <module>
    import FreeSimpleGUI as sg
ModuleNotFoundError: No module named 'FreeSimpleGUI'

(rvc-env) D:\RVC>pip install FreeSimpleGUI

**Comment by luoluoluo-plus** [comment]
“pip install FreeSimpleGUI”     it work

**Comment by AmmarkoV** [comment]
Thank you!
python3 -m pip install FreeSimpleGUI 
and change in gui_v1.py

from
    import PySimpleGUI as sg
to
    import FreeSimpleGUI as sg

and it works <3

**Pull request merged**
