### PR TITLE
fix flow

### PR DESCRIPTION
**Pull request by Tps-F**
# Pull request checklist

- [x] The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- [x] Make sure you are requesting the right branch: `dev`.
- [x] Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- [x] Ensure all tests are passing.
- [x] Ensure linting is passing.

# PR type

- Bug fixre

# Description

Fixed `AttributeError: 'tuple' object has no attribute 'split'` during onnx export.

### CODE REVIEW

**Review by fumiama — APPROVED** [review]

**Review by RVC-Boss — APPROVED** [review]

**Comment by artificalaudio** [comment]
that change seems to break using the model in simple onnx inference: 

`Reshape node. Name:'/enc_p/encoder/attn_layers.0/Reshape_10' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,2,20199}, requested shape:{1,2,101,199}`

**Comment by codename0og** [comment]
> that change seems to break using the model in simple onnx inference:
> 
> `Reshape node. Name:'/enc_p/encoder/attn_layers.0/Reshape_10' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,2,20199}, requested shape:{1,2,101,199}`

yea, unfortunately, issues still persist.
You gotta fallback to 0816 exporting or I may handle you the onnx export components' ported files to 1006

**Comment by artificalaudio** [comment]
> > that change seems to break using the model in simple onnx inference:
> > `Reshape node. Name:'/enc_p/encoder/attn_layers.0/Reshape_10' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,2,20199}, requested shape:{1,2,101,199}`
> 
> yea, unfortunately, issues still persist. You gotta fallback to 0816 exporting or I may handle you the onnx export components' ported files to 1006
> 
> but on a side note, I believe that either onnx export script, so core, needs adjustements in some way or either changes done, in 08XX or 1XXX releases, to: attentions, commons, modules, transforms - caused the whole process to fail somewhere along the way

Ok thank you for letting me know this. 

Just throwing this out there, Onnxruntime's latest version was released three weeks ago: https://github.com/microsoft/onnxruntime/releases

Can we be sure the problem is not an external change that has broken onnx export?

**Comment by codename0og** [comment]
> > > that change seems to break using the model in simple onnx inference:
> > > `Reshape node. Name:'/enc_p/encoder/attn_layers.0/Reshape_10' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,2,20199}, requested shape:{1,2,101,199}`
> > 
> > 
> > yea, unfortunately, issues still persist. You gotta fallback to 0816 exporting or I may handle you the onnx export components' ported files to 1006
> > but on a side note, I believe that either onnx export script, so core, needs adjustements in some way or either changes done, in 08XX or 1XXX releases, to: attentions, commons, modules, transforms - caused the whole process to fail somewhere along the way
> 
> Ok thank you for letting me know this.
> 
> Just throwing this out there, Onnxruntime's latest version was released three weeks ago: https://github.com/microsoft/onnxruntime/releases
> 
> Can we be sure the problem is not an external change that has broken onnx export?

it's not the case because onnx is used for exporting ( onnx = framework )  while onnx runtime is a separate package, used for inference.  Current onnx is 15   and onnx runtime indeed 16.3.1 yet, runtime is backwards compatible with older onnx operators set.
Aside, I tested various combos, onnx 14/15 exporting ( operator sets 15, 14, 23 ) and few runtime versions

**Comment by codename0og** [comment]
I just think that in general rvc should get updated with better onnx handling - Dynamo exporting rather than export script method

**Comment by Tps-F** [comment]
This is just a bugfix and I will fix the onnx related issues you mentioned in the future

**Pull request merged**
