### PR TITLE
Voice Cloning Evals v0.1

### PR DESCRIPTION
**Pull request by pursuitcurves**
# Pull request checklist

- [x] The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- [x] Make sure you are requesting the right branch: `dev`.
- [x] Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- [x] Ensure all tests are passing.
- [x] Ensure linting is passing.

# PR type

- new feature

# Description
- This pull request adds evaluation modules to the repository allowing quantifiable insights on how close the cloned speaker is to the original and the intelligibility of the outputs generated.
- I have utilised NVIDIA's Titanet to compare embeddings from the dataset and synthesized speech, providing a similarity score. Additionally, I used OpenAI's whisper text-to-speech and calculated the word error rate for testing output intelligibility.
- This impacts the project by providing more actionable data on the effectiveness of the voice cloning, paving the way for additional improvements based on this data.
- Future plans will extend this evaluation to include more domains within both speaker similarity and intelligibility, further refining the effectiveness of the voice cloning.

# Screenshot

image

### CODE REVIEW

**Comment by Tps-F** [comment]
Looks good
Will do some tests and Approve

**Comment by Pevernow** [comment]
@RVC-Boss

**Comment by blaise-tk** [comment]
> Great job, but no Chinese?

If you want people to contribute to the code, I think the developers should think about changing the code base to English, as well as the main documentation.

**Comment by Tps-F** [comment]
@fumiama @blaise-tk @Pevernow 
I am now changing the structure of the i18n file. Maybe that will help

**Pull request closed without merging**
