### PR TITLE
Add .sh run script for macOS & linux, fix error on macs with low vram.

### PR DESCRIPTION
**Pull request by Naozumi520**
macOS users running RVC often experience issues due to the platform differences. 
Therefore, splitting requirements.txt for macOS is necessary. For example: training feature index on macOS only doable with faiss-cpu 1.7.0 (#695), higher or lower version will cause an error and directly crash RVC. Splitting out requirements.txt for macOS users is obviously much better than continuing to use the old version package for all platform users.

Also it makes it easier to set up the entire environment by running .sh files for macOS and Linux users. This script install missing dependencies for example, and install python3.8 (bets for this project) automatically.

### CODE REVIEW

**Comment by Tps-F** [comment]
As #252 and #311, faiss-cpu1.7.0 fails to install (I also tried it in M1 environment, but no luck).
Did it work?

**Comment by Naozumi520** [comment]
Yes :D
It worked for me, and feature index training worked without issue!

**Comment by Tps-F** [comment]
It was still not working in my environment. But it is a great PR and I want to merge it.
Can you tell me what version of swig you use?

**Comment by Naozumi520** [comment]
Swig was not installed on my Mac? 

```
naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 % swig -version
zsh: command not found: swig
naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 % which swig
swig not found
naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 %
```

I installed faiss with pip btw.

**Comment by Naozumi520** [comment]
I installed faiss-cpu in a virtual environment and the it installed without any problem?

```
naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 % python3.8 -m venv faiss_test
naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 % source faiss_test/bin/activate
(faiss_test) naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 % pip install faiss-cpu==1.7.0
Collecting faiss-cpu==1.7.0
  Using cached faiss_cpu-1.7.0-cp38-cp38-macosx_10_14_x86_64.whl (1.9 MB)
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.7.0
WARNING: You are using pip version 21.1.1; however, version 23.1.2 is available.
You should consider upgrading via the '/Users/naozumi/Downloads/RVC/Retrieval-based-Voice-Conversion-WebUI-updated0618v2/faiss_test/bin/python3.8 -m pip install --upgrade pip' command.
(faiss_test) naozumi@n218103174213 Retrieval-based-Voice-Conversion-WebUI-updated0618v2 %
```

**Comment by Naozumi520** [comment]
I see the reason. I'm using intel Macs and it seems faiss-cpu@1.7.0 have the pre-built wheel for x86_64 arch.
https://pypi.tuna.tsinghua.edu.cn/simple/faiss-cpu/

I checked the list and did not see there's arm version... D:

**Review by fumiama — APPROVED** [review]

**Review by fumiama — CHANGES_REQUESTED** [review]
I suggest you remove the `requirements_macOS.txt` file and let user to decide how and which version to install since the pip installation seems no problem in my M1 environment.

**Comment by Naozumi520** [comment]
I've made changes to the `.sh` file and deleted `requirements_macOS.txt `. 👍

**Review by fumiama — APPROVED** [review]
good job.

**Comment by ozpower** [comment]
I almost got everything installed, but got stuck at this part: ImportError: cannot import name 'FFmpeg' from 'ffmpy' (/usr/local/lib/python3.8/site-packages/ffmpy/init.py) any help please?

**Comment by an-internet-user001** [comment]
same here:  ImportError: cannot import name 'FFprobe' from 'ffmpy'

i get this every time i try to use the "run.sh" script

**Pull request merged**
