### PR TITLE
feat: add fcpe to pipeline

### PR DESCRIPTION
**Pull request by rsxdalv**
# Pull request checklist

- [x] The PR has a proper title. Use [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages). (No more branch-name title please)
- [x] Make sure you are requesting the right branch: `dev`.
- [x] Make sure this is ready to be merged into the relevant branch. Please don't create a PR and let it hang for a few days.
- [x] Ensure all tests are passing.
- [x] Ensure linting is passing.

# PR type

- new feature based on realtime_vc

# Description

- Add fcpe to the pipeline, allowing it to be used when using the command line.

### CODE REVIEW

**Comment by Kamikadashi** [comment]
It seems to be working fine. So far, it doesn’t feel much faster for my use case, but this requires further testing.

**Comment by blaise-tk** [comment]
should be added to the ui too. also maybe for training extraction?

**Comment by rsxdalv** [comment]
I agree, it was in one of the UI parts but not the other, so I didn't
notice the gap before.

**Comment by KakaruHayate** [comment]
Very good job, I will be working on the torch_musa backend after the merger 
(fcpe is the only supported pitch extractor in torch_musa)

**Comment by blaise-tk** [comment]
it is possible to add as an extraction method?

**Review by fumiama — APPROVED** [review]

**Pull request merged**
