### PR TITLE
Add directML support to RVC for AMD & Intel GPU supported

### PR DESCRIPTION
**Pull request by pamzerbhu**

### CODE REVIEW

**Review by fumiama — CHANGES_REQUESTED** [review]
建议直接做到gui.py中，好处是以后gui有什么更改不用改两个地方。

**Comment by RVC-Boss** [comment]
@fumiama 先和N卡推理隔离，保证原有N卡用户的体验一定不会受到影响，后面我再抽时间合并

**Comment by jponte84** [comment]
Hi !
Does it support for infer or only for training ?

**Comment by Acrivec** [comment]
> Hi ! Does it support for infer or only for training ?

Well, for me gpu works on pitch extract, then it falls down to CPU on training. 7900xtx

**Pull request merged**
