### PR TITLE
some change precision audio processing

### PR DESCRIPTION
**Pull request by autumnmotor**
I try to change audio processing for more high precision.

1: librosa.load

in librosa.load, default res_type of input , res_type='soxr_hq' (High Quality)
but, res_type=‘soxr_vhq’ is more better (Very High Quality)

see https://librosa.org/doc/main/generated/librosa.load.html

2: my_util.load_audio

my_util.load_audio is audio convert proccess by ffmpeg.
but output is 16bit audio any time.
in digital audio processing, its should be 32bit float for precision.

3: Type of HighPassFilter

scipy.signal.filtfilt is zero phased filter.
zero phased filter causes pre-ringing noise.

> https://www.google.com/search?q=pre-ringing+noise&oq=pre-ringing+noise

I think we should adopt scipy.signal.lfilter instead.
It doesn't have pre-ringing noise, but it causes "phase delay" instead.
but, I think it's better to use scipy.signal.lfilter for voice conversion processing where noise can cause quality degradation.

Thank you for read my poor english!

### CODE REVIEW

**Review by fumiama — COMMENTED** [review]
@liujing04 佬，可以看看这个对程序行为是否有影响😂

**Comment by RVC-Boss** [comment]
extract_f0_print.py
x, sr = librosa.load(path, self.fs, res_type='soxr_vhq')
ModuleNotFoundError: No module named 'soxr'
my librosa verison is 0.9.2

**Comment by autumnmotor** [comment]
On my pc it works fine...
librosa.__version__ ->’ 0.8.1’
soxr.__version__ -> '0.3.5'

**Comment by fumiama** [comment]
Maybe we should add soxr to requirements.

**Pull request merged**
